from .component_parse_prompt import TEMPLATE as KERNEL_COMPONENT_PARSE_PROMPT_TEMPLATE
from .rewrite_prompt import TEMPLATE as KERNEL_REWRITE_PROMPT_TEMPLATE

__all__ = [
    "KERNEL_COMPONENT_PARSE_PROMPT_TEMPLATE",
    "KERNEL_REWRITE_PROMPT_TEMPLATE",
]