"""
TextGrad Iterative Prompt Optimizer — Real Backpropagation via textgrad Library

Standard LLM-based prompt optimization (the "single-shot" approach) asks a model to
rewrite a prompt once and accept the output. This is equivalent to taking one step
of gradient descent with an arbitrarily large learning rate and no loss function —
the update is unguided and may overshoot, undershoot, or solve a different problem
than the user intended. The result is a prompt that is different, but not provably
better.

TextGrad (Yuksekgonul et al., 2024, "TextGrad: Automatic 'Differentiation' via Text",
Stanford) introduces a framework that mirrors PyTorch's autograd for text. Instead of
numerical gradients, the "gradient" is a natural-language critique generated by an
evaluator LLM. Instead of a loss function, a TextLoss prompt describes the quality
criteria. The update step is performed by an optimizer LLM that rewrites the variable
(the prompt) based on the critique to reduce the loss.

The iterative loop structure is:
  1. Forward pass: the prompt variable is evaluated against the TextLoss rubric.
  2. Backward pass: the evaluator LLM generates a natural-language critique describing
     exactly which TCRTE dimensions are violated and why.
  3. Update step: the optimizer LLM rewrites the prompt attempting to resolve all
     critiques from step 2.
  4. Repeat for N iterations (default: 3).

Each iteration produces a checkpoint. The three checkpoints map to the three prompt
variants the APOST optimizer normally returns: the first checkpoint (one iteration)
is conservative and makes targeted adjustments; the third checkpoint (full three
iterations) is the most aggressively refined version. This gives the user the actual
optimization trajectory rather than three arbitrary single-shot variations.

When to use this optimizer:
  Select the "textgrad" framework when the raw prompt has structural issues that
  standard template injection cannot address — for example, contradictory constraints,
  ambiguous scope, or a task definition that becomes internally inconsistent once
  expanded. The iterative critique loop surfaces these problems explicitly.

When NOT to use this optimizer:
  For simple prompts where the single-shot builder already produces high-quality output,
  TextGrad is unnecessary overhead. For reasoning models (o-series, extended thinking),
  the reasoning-aware framework is more appropriate. For very long prompts (> 4,000
  tokens), the token cost per iteration becomes significant.

Cost: 3 LLM call pairs per run (1 evaluator + 1 optimizer per iteration × 3 iterations
= 6 total internal calls, routed through the textgrad library). The model used for
both evaluator and optimizer is the same model the user selected for optimization —
no additional API keys or models are required.
Latency: 3-5× the latency of a single-shot optimization (three full round-trips).
Quality: consistently outperforms single-shot on prompts with structural defects;
comparable to single-shot on already well-formed prompts.
"""

import logging
from typing import Optional

logger = logging.getLogger(__name__)

# ──────────────────────────────────────────────────────────────────────────────
# TextLoss rubric — what the evaluator critiques at each iteration.
# Grounded in TCRTE dimensions so the critique is structured, not freeform.
# ──────────────────────────────────────────────────────────────────────────────
_TCRTE_LOSS_PROMPT = """
Evaluate the following system prompt against the TCRTE framework for professional
prompt engineering. Identify every violation across these five dimensions:

Task (T): Is the primary action clearly expressed with an imperative verb? Is the
expected output measurable? Are constraints specified? Is success verifiable?

Context (C): Is the domain grounded? Is the data source described? Is temporal scope
stated?

Role (R): Is an expert persona declared? Is seniority or experience quantified? Are
behavioural priorities stated?

Tone (T): Is the formality register named? Is the target audience identified? Are
hedging and speculative language prohibited?

Execution (E): Is the output format specified? Is there a length constraint? Are
prohibited output elements named?

List EVERY violation found as a numbered list. For each violation state:
(a) which dimension is affected, (b) what is missing or unclear, (c) what specific
text change would fix it. If a dimension is fully satisfied, state "PASS" for it.
Do not offer general praise — this critique drives prompt improvement.
""".strip()


async def run_textgrad_optimization(
    raw_prompt: str,
    provider: str,
    model_id: str,
    api_key: str,
    n_iterations: int = 3,
) -> dict[str, str]:
    """
    Run the TextGrad iterative optimization loop.

    Returns a dict with keys:
      "conservative"  — prompt after iteration 1 (targeted adjustments)
      "structured"    — prompt after iteration 2 (deeper restructuring)
      "advanced"      — prompt after iteration 3 (fully refined)
      "final_loss"    — the textual critique from the last iteration (for logging/display)

    Falls back to returning three copies of the raw_prompt with an error note if
    the textgrad library raises any exception, so the route never 500s because of
    TextGrad failures.
    """
    try:
        import textgrad as tg

        # Configure the engine for the provider + model the user chose.
        # textgrad uses litellm under the hood, so the model string format matters.
        engine = _build_textgrad_engine(provider, model_id, api_key)
        tg.set_backward_engine(engine, override=True)

        # The system prompt variable — this is what gets optimized.
        system_prompt_var = tg.Variable(
            raw_prompt,
            requires_grad=True,
            role_description=(
                "A system prompt that will be sent to an LLM to guide its behaviour. "
                "Its quality is measured against the TCRTE framework for professional "
                "prompt engineering."
            ),
        )

        loss_fn = tg.TextLoss(_TCRTE_LOSS_PROMPT, engine=engine)
        optimizer = tg.TGD(parameters=[system_prompt_var], engine=engine)

        checkpoints: list[str] = []

        for iteration in range(n_iterations):
            loss = loss_fn(system_prompt_var)   # forward: evaluator generates critique
            loss.backward()                      # backward: critique propagates to variable
            optimizer.step()                     # update: optimizer rewrites the prompt
            optimizer.zero_grad()                # reset for next iteration
            checkpoints.append(system_prompt_var.value)
            logger.debug("TextGrad iteration %d complete.", iteration + 1)

        # Map checkpoints to the three APOST variant slots.
        # If n_iterations < 3, pad with the final checkpoint.
        while len(checkpoints) < 3:
            checkpoints.append(checkpoints[-1] if checkpoints else raw_prompt)

        final_critique = str(loss) if "loss" in dir() else ""

        return {
            "conservative": checkpoints[0],
            "structured":   checkpoints[1],
            "advanced":     checkpoints[2],
            "final_loss":   final_critique,
        }

    except ImportError:
        logger.error("textgrad library not installed. Run: uv add textgrad")
        return _fallback_variants(raw_prompt, error="textgrad not installed")

    except Exception as exc:
        logger.error("TextGrad optimization failed: %s", exc, exc_info=True)
        return _fallback_variants(raw_prompt, error=str(exc))


def _build_textgrad_engine(provider: str, model_id: str, api_key: str):
    """
    Build a textgrad ChatEngine for the given provider.
    TextGrad uses litellm internally, so we format the model string accordingly.
    """
    import os
    import textgrad as tg

    # Inject the API key into the environment for litellm to pick up.
    provider_lower = provider.lower()
    if provider_lower == "openai":
        os.environ["OPENAI_API_KEY"] = api_key
        engine_model = model_id  # litellm OpenAI format: "gpt-4o" etc.
    elif provider_lower == "anthropic":
        os.environ["ANTHROPIC_API_KEY"] = api_key
        engine_model = f"claude/{model_id}"  # litellm Anthropic format
    elif provider_lower == "google":
        os.environ["GEMINI_API_KEY"] = api_key
        engine_model = f"gemini/{model_id}"  # litellm Gemini format
    else:
        # Generic fallback — let litellm try to parse the model_id
        engine_model = model_id

    return tg.get_engine(engine_model)


def _fallback_variants(raw_prompt: str, error: str) -> dict[str, str]:
    """Return safe fallback output when TextGrad fails."""
    note = f"\n\n[TextGrad optimization unavailable: {error}]"
    return {
        "conservative": raw_prompt + note,
        "structured":   raw_prompt + note,
        "advanced":     raw_prompt + note,
        "final_loss":   error,
    }
