from .failure_mode_analysis_prompt import TEMPLATE as FAILURE_MODE_ANALYSIS_PROMPT_TEMPLATE
from .structural_rewrite_prompt import TEMPLATE as STRUCTURAL_REWRITE_PROMPT_TEMPLATE

__all__ = [
    "FAILURE_MODE_ANALYSIS_PROMPT_TEMPLATE",
    "STRUCTURAL_REWRITE_PROMPT_TEMPLATE",
]