from .criticality_analysis_prompt import TEMPLATE as CRITICALITY_ANALYSIS_PROMPT_TEMPLATE
from .strategic_rewrite_prompt import TEMPLATE as STRATEGIC_REWRITE_PROMPT_TEMPLATE

__all__ = [
    "CRITICALITY_ANALYSIS_PROMPT_TEMPLATE",
    "STRATEGIC_REWRITE_PROMPT_TEMPLATE",
]