from .parse_prompt import TEMPLATE as SAMMO_PARSE_PROMPT_TEMPLATE
from .mutation_prompt import TEMPLATE as SAMMO_MUTATION_PROMPT_TEMPLATE

__all__ = [
    "SAMMO_PARSE_PROMPT_TEMPLATE",
    "SAMMO_MUTATION_PROMPT_TEMPLATE",
]